/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.scoping;

import org.xtext.example.script.scoping.ScriptScopeProvider;

public abstract class AbstractRulesScopeProvider extends ScriptScopeProvider {
}
