/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script.script.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.xtext.xbase.impl.XBlockExpressionImpl;

import org.xtext.example.script.script.Script;
import org.xtext.example.script.script.ScriptPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScriptImpl extends XBlockExpressionImpl implements Script
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScriptImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ScriptPackage.Literals.SCRIPT;
  }

} //ScriptImpl
