/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScriptAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/script/parser/antlr/internal/InternalScript.tokens");
	}
}
