/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.script.parser.antlr.internal.InternalScriptParser;
import org.xtext.example.script.services.ScriptGrammarAccess;

public class ScriptParser extends AbstractAntlrParser {

	@Inject
	private ScriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalScriptParser createParser(XtextTokenStream stream) {
		return new InternalScriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}

	public ScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
