/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules;

import org.xtext.example.rules.RulesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RulesStandaloneSetup extends RulesStandaloneSetupGenerated {
  public static void doSetup() {
    RulesStandaloneSetup _rulesStandaloneSetup = new RulesStandaloneSetup();
    _rulesStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
