/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules;

import org.xtext.example.rules.AbstractRulesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RulesRuntimeModule extends AbstractRulesRuntimeModule {
}
