/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.sitemap.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sitemap.sitemap.NonLinkableWidget;
import org.xtext.example.sitemap.sitemap.SitemapPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Non Linkable Widget</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NonLinkableWidgetImpl extends WidgetImpl implements NonLinkableWidget
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NonLinkableWidgetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SitemapPackage.Literals.NON_LINKABLE_WIDGET;
  }

} //NonLinkableWidgetImpl
