/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.sitemap.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.sitemap.sitemap.SitemapPackage;
import org.xtext.example.sitemap.sitemap.Text;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TextImpl extends LinkableWidgetImpl implements Text
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SitemapPackage.Literals.TEXT;
  }

} //TextImpl
