/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.rules.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.rules.rules.EventTrigger;
import org.xtext.example.rules.rules.RulesPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EventTriggerImpl extends MinimalEObjectImpl.Container implements EventTrigger
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EventTriggerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RulesPackage.Literals.EVENT_TRIGGER;
  }

} //EventTriggerImpl
