/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.rules.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.rules.rules.RulesPackage;
import org.xtext.example.rules.rules.SystemTrigger;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SystemTriggerImpl extends EventTriggerImpl implements SystemTrigger
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemTriggerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RulesPackage.Literals.SYSTEM_TRIGGER;
  }

} //SystemTriggerImpl
