/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.rules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.rules.rules.RulesPackage#getEventTrigger()
 * @model
 * @generated
 */
public interface EventTrigger extends EObject
{
} // EventTrigger
