/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.rules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System On Startup Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.rules.rules.RulesPackage#getSystemOnStartupTrigger()
 * @model
 * @generated
 */
public interface SystemOnStartupTrigger extends SystemTrigger
{
} // SystemOnStartupTrigger
