/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractScriptScopeProvider extends XbaseBatchScopeProvider {
}
