/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RulesStandaloneSetup extends RulesStandaloneSetupGenerated {

	def static void doSetup() {
		new RulesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
