/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence;

import org.xtext.example.persistence.PersistenceStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PersistenceStandaloneSetup extends PersistenceStandaloneSetupGenerated {
  public static void doSetup() {
    PersistenceStandaloneSetup _persistenceStandaloneSetup = new PersistenceStandaloneSetup();
    _persistenceStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
