/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence;

import org.xtext.example.persistence.AbstractPersistenceRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PersistenceRuntimeModule extends AbstractPersistenceRuntimeModule {
}
