/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script;

import org.xtext.example.script.AbstractScriptRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ScriptRuntimeModule extends AbstractScriptRuntimeModule {
}
