/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script;

import org.xtext.example.script.ScriptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ScriptStandaloneSetup extends ScriptStandaloneSetupGenerated {
  public static void doSetup() {
    ScriptStandaloneSetup _scriptStandaloneSetup = new ScriptStandaloneSetup();
    _scriptStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
