/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.items.items;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.items.items.ItemModel#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.items.items.ItemsPackage#getItemModel()
 * @model
 * @generated
 */
public interface ItemModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.items.items.ModelItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see org.xtext.example.items.items.ItemsPackage#getItemModel_Items()
   * @model containment="true"
   * @generated
   */
  EList<ModelItem> getItems();

} // ItemModel
