/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.items.items;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.items.items.ModelBinding#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.items.items.ModelBinding#getConfiguration <em>Configuration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.items.items.ItemsPackage#getModelBinding()
 * @model
 * @generated
 */
public interface ModelBinding extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.items.items.ItemsPackage#getModelBinding_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.items.items.ModelBinding#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Configuration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configuration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configuration</em>' attribute.
   * @see #setConfiguration(String)
   * @see org.xtext.example.items.items.ItemsPackage#getModelBinding_Configuration()
   * @model
   * @generated
   */
  String getConfiguration();

  /**
   * Sets the value of the '{@link org.xtext.example.items.items.ModelBinding#getConfiguration <em>Configuration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Configuration</em>' attribute.
   * @see #getConfiguration()
   * @generated
   */
  void setConfiguration(String value);

} // ModelBinding
