/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.script.validation;

import org.xtext.example.script.validation.AbstractScriptValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ScriptValidator extends AbstractScriptValidator {
}
