/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPersistenceScopeProvider extends DelegatingScopeProvider {
}
