/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence.persistence;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Config</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.persistence.persistence.PersistencePackage#getAllConfig()
 * @model
 * @generated
 */
public interface AllConfig extends EObject
{
} // AllConfig
