/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap;

import org.xtext.example.sitemap.SitemapStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SitemapStandaloneSetup extends SitemapStandaloneSetupGenerated {
  public static void doSetup() {
    SitemapStandaloneSetup _sitemapStandaloneSetup = new SitemapStandaloneSetup();
    _sitemapStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
