/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap;

import org.xtext.example.sitemap.AbstractSitemapRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SitemapRuntimeModule extends AbstractSitemapRuntimeModule {
}
