/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class SitemapScopeProvider extends AbstractSitemapScopeProvider {

}
