/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.sitemap;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frame</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sitemap.sitemap.SitemapPackage#getFrame()
 * @model
 * @generated
 */
public interface Frame extends LinkableWidget
{
} // Frame
