/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.sitemap;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Linkable Widget</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sitemap.sitemap.SitemapPackage#getNonLinkableWidget()
 * @model
 * @generated
 */
public interface NonLinkableWidget extends Widget
{
} // NonLinkableWidget
