/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.sitemap;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.sitemap.sitemap.SitemapPackage#getSitemapModel()
 * @model
 * @generated
 */
public interface SitemapModel extends EObject
{
} // SitemapModel
