/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence.persistence.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.persistence.persistence.AllConfig;
import org.xtext.example.persistence.persistence.PersistencePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>All Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AllConfigImpl extends MinimalEObjectImpl.Container implements AllConfig
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PersistencePackage.Literals.ALL_CONFIG;
  }

} //AllConfigImpl
