/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.items;

import org.xtext.example.items.AbstractItemsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ItemsRuntimeModule extends AbstractItemsRuntimeModule {
}
