/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.items;

import org.xtext.example.items.ItemsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ItemsStandaloneSetup extends ItemsStandaloneSetupGenerated {
  public static void doSetup() {
    ItemsStandaloneSetup _itemsStandaloneSetup = new ItemsStandaloneSetup();
    _itemsStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
