/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.items.items.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.items.items.ItemsPackage;
import org.xtext.example.items.items.ModelNormalItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model Normal Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ModelNormalItemImpl extends ModelItemImpl implements ModelNormalItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelNormalItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ItemsPackage.Literals.MODEL_NORMAL_ITEM;
  }

} //ModelNormalItemImpl
