/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.sitemap.parser.antlr.internal.InternalSitemapParser;
import org.xtext.example.sitemap.services.SitemapGrammarAccess;

public class SitemapParser extends AbstractAntlrParser {

	@Inject
	private SitemapGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSitemapParser createParser(XtextTokenStream stream) {
		return new InternalSitemapParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SitemapModel";
	}

	public SitemapGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SitemapGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
