/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SitemapAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/sitemap/parser/antlr/internal/InternalSitemap.tokens");
	}
}
