/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSitemapValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.sitemap.sitemap.SitemapPackage.eINSTANCE);
		return result;
	}
	
}
