/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.rules.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.rules.parser.antlr.internal.InternalRulesParser;
import org.xtext.example.rules.services.RulesGrammarAccess;

public class RulesParser extends AbstractAntlrParser {

	@Inject
	private RulesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRulesParser createParser(XtextTokenStream stream) {
		return new InternalRulesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RuleModel";
	}

	public RulesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RulesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
