/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PersistenceRuntimeModule extends AbstractPersistenceRuntimeModule {
}
