/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PersistenceAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/persistence/parser/antlr/internal/InternalPersistence.tokens");
	}
}
