/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.persistence.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.persistence.parser.antlr.internal.InternalPersistenceParser;
import org.xtext.example.persistence.services.PersistenceGrammarAccess;

public class PersistenceParser extends AbstractAntlrParser {

	@Inject
	private PersistenceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPersistenceParser createParser(XtextTokenStream stream) {
		return new InternalPersistenceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PersistenceModel";
	}

	public PersistenceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PersistenceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
