/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.xtext.example.sitemap.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSitemapScopeProvider extends DelegatingScopeProvider {
}
